instanceId: "18662598"
http:
  listener:
    host: "0.0.0.0"
    port: "8081"
  requester:
    customer:
      papi:
        host: "customer-papi-app888888.us-e2.cloudhub.io"
        port: ""
        pathCustomerRegistration: "/api/customers/registration"

    
        
            
                
                    
                        
                            
                                
                                    
                                        
                                            
                                                
                                                    
                                                        
                                                            
                                                                
                                                                    
                                                                        
                                                                            
                                                                                
                                                                                    
                                                                                        
                                                                                            
                                                                                                
                                                                                                    
                                                                                                        
                                                                                                            
                                                                                                                
                                                                                                                    
                                                                                                                        
                                                                                                                            
                                                                                                                                
                                                                                                                                    
                                                                                                                                            
sfdc:
  username: "kumarmuletraining1@gmail.com"
  password: "ABCD@1234@abcd"
  securityToken: "whLO4wdVTLZnB1WGphxoZpl4"



